/**
 * Simulates OpenAI API with realistic delay
 */
export interface MockOpenAIResponse {
    answer: string;
    tokensUsed: number;
    model: string;
    latencyMs: number;
  }
  
  export async function mockOpenAICall(question: string): Promise<MockOpenAIResponse> {
    // Simulate API latency: 500ms - 2500ms (realistic for GPT-4)
    const latencyMs = Math.floor(Math.random() * 2000) + 500;
    await new Promise((resolve) => setTimeout(resolve, latencyMs));
  
    // Simulate token count (rough estimate: 1 token ≈ 4 chars)
    const tokensUsed = Math.ceil(question.length / 4) + Math.floor(Math.random() * 100) + 50;
  
    const responses = [
      `Based on your question about "${question.substring(0, 30)}...", here's what I found: This is a simulated AI response that would typically contain detailed information, analysis, and actionable insights. In a production environment, this would be generated by an actual LLM like GPT-4 or Claude.`,
      `Great question! Regarding "${question.substring(0, 30)}...", the key considerations are: First, understand the context thoroughly. Second, apply domain-specific knowledge. Third, validate assumptions. Here's a comprehensive breakdown of what you need to know...`,
      `I've analyzed your query about "${question.substring(0, 30)}..." and here's my assessment: The most relevant approach involves systematic evaluation of available options, weighing trade-offs, and implementing evidence-based solutions. Let me elaborate on the key points...`,
    ];
  
    return {
      answer: responses[Math.floor(Math.random() * responses.length)],
      tokensUsed,
      model: 'gpt-4-mock',
      latencyMs,
    };
  }